apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mlflow-hook.fullname" . }}
  labels:
    {{- include "mlflow-hook.labels" . | nindent 4 }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "mlflow-hook.serviceAccountName" . }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: MLFLOW_TRACKING_URI
              value: "{{ .Values.config.MLFLOW_TRACKING_URI }}"
            - name: MLFLOW_MODEL_NAME
              value: "{{ .Values.config.MLFLOW_MODEL_NAME }}"
            - name: MLFLOW_STAGE
              value: "{{ .Values.config.MLFLOW_STAGE }}"
            - name: MLFLOW_DEPLOY_NAME
              value: "{{ .Values.config.MLFLOW_DEPLOY_NAME }}"
            - name: DEPLOY_NAMESPACE
              value: "{{ .Values.config.DEPLOY_NAMESPACE }}"
          restartPolicy: Never
