{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlflow-hook.serviceAccountName" . }}
  labels:
    {{- include "mlflow-hook.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: "{{ include "mlflow-hook.serviceAccountName" . }}:admin"
rules:
    - apiGroups: ["machinelearning.seldon.io"]
      resources: ["*"]
      verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: "{{ include "mlflow-hook.serviceAccountName" . }}:admin"
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: "seldon:admin"
subjects:
    - kind: ServiceAccount
      name: {{ include "mlflow-hook.serviceAccountName" . }}
      namespace: {{.Release.Namespace}}
{{- end }}
